import React, { createContext, useContext, useState, useEffect } from "react";

const CareerContext = createContext(null);

export function CareerProvider({ children }) {
  // Assessment Profile generated by AI
  const [assessmentProfile, setAssessmentProfile] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_profile");
    return val ? JSON.parse(val) : null;
  });

  // Careers recommended by AI based on profile
  const [recommendedCareers, setRecommendedCareers] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_recommended_careers");
    return val ? JSON.parse(val) : [];
  });

  // The active, fully detailed AI roadmap JSON
  const [activeRoadmap, setActiveRoadmap] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_active_roadmap");
    return val ? JSON.parse(val) : null;
  });

  // Weekly Test Scores history
  const [testScores, setTestScores] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_test_scores");
    return val ? JSON.parse(val) : [];
  });

  // Track overall goals: daily, weekly, monthly
  const [plannerGoals, setPlannerGoals] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_planner_goals");
    return val ? JSON.parse(val) : { daily: [], weekly: [], monthly: [] };
  });

  useEffect(() => {
    if (assessmentProfile) localStorage.setItem("skillnova_ai_profile", JSON.stringify(assessmentProfile));
    else localStorage.removeItem("skillnova_ai_profile");
  }, [assessmentProfile]);

  useEffect(() => {
    if (recommendedCareers.length > 0) localStorage.setItem("skillnova_ai_recommended_careers", JSON.stringify(recommendedCareers));
    else localStorage.removeItem("skillnova_ai_recommended_careers");
  }, [recommendedCareers]);

  useEffect(() => {
    if (activeRoadmap) localStorage.setItem("skillnova_ai_active_roadmap", JSON.stringify(activeRoadmap));
    else localStorage.removeItem("skillnova_ai_active_roadmap");
  }, [activeRoadmap]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_test_scores", JSON.stringify(testScores));
  }, [testScores]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_planner_goals", JSON.stringify(plannerGoals));
  }, [plannerGoals]);

  const clearAllData = () => {
    setAssessmentProfile(null);
    setRecommendedCareers([]);
    setActiveRoadmap(null);
    setTestScores([]);
    setPlannerGoals({ daily: [], weekly: [], monthly: [] });
  };

  const addTestScore = (scoreData) => {
    setTestScores(prev => [...prev, { ...scoreData, date: new Date().toISOString() }]);
  };

  return (
    <CareerContext.Provider
      value={{
        assessmentProfile, setAssessmentProfile,
        recommendedCareers, setRecommendedCareers,
        activeRoadmap, setActiveRoadmap,
        testScores, addTestScore,
        plannerGoals, setPlannerGoals,
        clearAllData
      }}
    >
      {children}
    </CareerContext.Provider>
  );
}

export function useCareer() {
  const context = useContext(CareerContext);
  if (!context) {
    throw new Error("useCareer must be used within a CareerProvider");
  }
  return context;
}
