import React, { createContext, useContext, useState, useEffect } from "react";

const CareerContext = createContext(null);

export function CareerProvider({ children }) {
  // Assessment Profile generated by AI
  const [assessmentProfile, setAssessmentProfile] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_profile");
    return val ? JSON.parse(val) : null;
  });

  // Careers recommended by AI based on profile
  const [recommendedCareers, setRecommendedCareers] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_recommended_careers");
    return val ? JSON.parse(val) : [];
  });

  // The active, fully detailed AI roadmap JSON
  const [activeRoadmap, setActiveRoadmap] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_active_roadmap");
    return val ? JSON.parse(val) : null;
  });

  // Weekly Test Scores history
  const [testScores, setTestScores] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_test_scores");
    return val ? JSON.parse(val) : [];
  });

  // AI Generated Daily Mission
  const [dailyMission, setDailyMission] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_daily_mission");
    return val ? JSON.parse(val) : null;
  });

  // Gamification: XP & Badges
  const [xp, setXp] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_xp");
    return val ? parseInt(val, 10) : 0;
  });

  const [badges, setBadges] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_badges");
    return val ? JSON.parse(val) : [];
  });

  // Smart Memory & Long Term Tracking
  const [weakTopics, setWeakTopics] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_weak_topics");
    return val ? JSON.parse(val) : [];
  });

  const [strongTopics, setStrongTopics] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_strong_topics");
    return val ? JSON.parse(val) : [];
  });

  const [totalStudyHours, setTotalStudyHours] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_study_hours");
    return val ? parseFloat(val) : 0;
  });

  const [learningStreak, setLearningStreak] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_streak");
    return val ? parseInt(val, 10) : 0;
  });

  const [projectsFinished, setProjectsFinished] = useState(() => {
    const val = localStorage.getItem("skillnova_ai_projects_finished");
    return val ? parseInt(val, 10) : 0;
  });

  useEffect(() => {
    if (assessmentProfile) localStorage.setItem("skillnova_ai_profile", JSON.stringify(assessmentProfile));
    else localStorage.removeItem("skillnova_ai_profile");
  }, [assessmentProfile]);

  useEffect(() => {
    if (recommendedCareers.length > 0) localStorage.setItem("skillnova_ai_recommended_careers", JSON.stringify(recommendedCareers));
    else localStorage.removeItem("skillnova_ai_recommended_careers");
  }, [recommendedCareers]);

  useEffect(() => {
    if (activeRoadmap) localStorage.setItem("skillnova_ai_active_roadmap", JSON.stringify(activeRoadmap));
    else localStorage.removeItem("skillnova_ai_active_roadmap");
  }, [activeRoadmap]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_test_scores", JSON.stringify(testScores));
  }, [testScores]);

  useEffect(() => {
    if (dailyMission) localStorage.setItem("skillnova_ai_daily_mission", JSON.stringify(dailyMission));
    else localStorage.removeItem("skillnova_ai_daily_mission");
  }, [dailyMission]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_xp", xp.toString());
  }, [xp]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_badges", JSON.stringify(badges));
  }, [badges]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_weak_topics", JSON.stringify(weakTopics));
  }, [weakTopics]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_strong_topics", JSON.stringify(strongTopics));
  }, [strongTopics]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_study_hours", totalStudyHours.toString());
  }, [totalStudyHours]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_streak", learningStreak.toString());
  }, [learningStreak]);

  useEffect(() => {
    localStorage.setItem("skillnova_ai_projects_finished", projectsFinished.toString());
  }, [projectsFinished]);

  const clearAllData = () => {
    setAssessmentProfile(null);
    setRecommendedCareers([]);
    setActiveRoadmap(null);
    setTestScores([]);
    setDailyMission(null);
    setXp(0);
    setBadges([]);
    setWeakTopics([]);
    setStrongTopics([]);
    setTotalStudyHours(0);
    setLearningStreak(0);
    setProjectsFinished(0);
  };

  const switchCareer = () => {
    // Archives current roadmap/mission, keeps profile and achievements
    setActiveRoadmap(null);
    setDailyMission(null);
    setTestScores([]);
  };

  const addTestScore = (scoreData) => {
    setTestScores(prev => [...prev, { ...scoreData, date: new Date().toISOString() }]);
    if (scoreData.xpEarned) {
      setXp(prev => prev + scoreData.xpEarned);
    }
    if (scoreData.weakAreas) {
      setWeakTopics(prev => {
        const newSet = new Set([...prev, ...scoreData.weakAreas]);
        return Array.from(newSet).slice(0, 10);
      });
    }
    if (scoreData.strongAreas) {
      setStrongTopics(prev => {
        const newSet = new Set([...prev, ...scoreData.strongAreas]);
        return Array.from(newSet).slice(0, 10);
      });
    }
  };

  const awardBadge = (badge) => {
    if (!badges.find(b => b.id === badge.id)) {
      setBadges(prev => [...prev, badge]);
    }
  };

  return (
    <CareerContext.Provider
      value={{
        assessmentProfile, setAssessmentProfile,
        recommendedCareers, setRecommendedCareers,
        activeRoadmap, setActiveRoadmap,
        testScores, addTestScore,
        dailyMission, setDailyMission,
        xp, setXp,
        badges, awardBadge,
        weakTopics, setWeakTopics,
        strongTopics, setStrongTopics,
        totalStudyHours, setTotalStudyHours,
        learningStreak, setLearningStreak,
        projectsFinished, setProjectsFinished,
        clearAllData, switchCareer
      }}
    >
      {children}
    </CareerContext.Provider>
  );
}

export function useCareer() {
  const context = useContext(CareerContext);
  if (!context) {
    throw new Error("useCareer must be used within a CareerProvider");
  }
  return context;
}
